### PR TITLE
Create matches for 1.9 to 1.11.2

### PR DESCRIPTION
**Pull request by Earthcomputer**
Creates matches for:
- 1.9
- 1.9.1
- 1.9.2
- 1.9.3
- 1.9.4
- 1.10
- 1.10.1
- 1.10.2
- 1.11
- 1.11.1
- 1.11.2

### CODE REVIEW

**Review by l1ving — APPROVED** [review]

**Comment by hYdos** [comment]
how complete are the matches? there is no proper way to verify matches sadly so i just have to go off trust

**Comment by Earthcomputer** [comment]
@hYdos they are complete.

**Comment by TheGlitch76** [comment]
Perhaps this would be a good time to consider moving release-level matches into their own folder?
With all of these matches that do direct release hops mixed in with snapshot matches, it's confusing to follow what goes where.

**Comment by hYdos** [comment]
i like that idea @TheGlitch76 . @Earthcomputer mind if you do this in your pr?

**Comment by hYdos** [comment]
REPO_DIR/matches/1.12.x/1.12-SomeSnapshotW18A.match for example.

**Comment by TheGlitch76** [comment]
What I had in mind was closer to:
`matches/releases/1.12-1.12.1.match` (direct version-to-version)
`matches/snapshots/1.12-00w00a.match` (per-snapshot)
But your idea works as well.

**Comment by TheGlitch76** [comment]
Maybe the best solution would be:
`matches/releases/a-b.match` (all release-level matches in that folder
`matches/snapshots/1.0.X/a-b.match`

**Comment by hYdos** [comment]
> 
> 
> Maybe the best solution would be:
> `matches/releases/a-b.match` (all release-level matches in that folder)
> `matches/snapshots/1.0.X/a-b.match`

i like your system more honestly. @Earthcomputer please use what glitch speicified

**Comment by Earthcomputer** [comment]
Could also separate backwards/forwards matches

**Pull request merged**
