### PR TITLE
1.8.9 ->1.8 + 15w14a april fool

### PR DESCRIPTION
**Pull request by arthurbambou**
depends on #35

### CODE REVIEW

**Review by BluCobalt — APPROVED** [review]
🗿

**Comment by arthurbambou** [comment]
one more person review please?

**Review by PseudoDistant — APPROVED** [review]
YOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by PseudoDistant** [comment]
PINK WITHER FTW

**Pull request merged**
