### PR TITLE
Fix 1.7-1.7.9 corrupt mappings

### PR DESCRIPTION
**Pull request by HowardZHY**

### CODE REVIEW

**Comment by HowardZHY** [comment]
This fixes 1.7.9 failed to launch and 1.7.X mod compact.
Plz upgrade maven files after merge.

**Review by BoogieMonster1O1 — APPROVED** [review]

**Comment by HowardZHY** [comment]
@hYdos @arthurbambou review it

**Review by hYdos — APPROVED** [review]

**Comment by HowardZHY** [comment]
plz also update maven and yarn

**Comment by arthurbambou** [comment]
maven is already updated

**Comment by arthurbambou** [comment]
or maybe not bruh

**Comment by HowardZHY** [comment]
update intermediary maven when

**Pull request merged**
