### PR TITLE
1.12.2 -> 1.12.1 matches + Generated Intermediaries

### PR DESCRIPTION
**Pull request by halotroop2288**
Part one of backwards matching from our most complete version.

### CODE REVIEW

**Comment by ENDERZOMBI102** [comment]
:iapprove:

**Comment by halotroop2288** [comment]
@ENDERZOMBI102 Great. Can you actually hit the approve button though?

**Comment by ENDERZOMBI102** [comment]
> @ENDERZOMBI102 Great. Can you actually hit the approve button though?

nope, i have no such button

**Review by ENDERZOMBI102 — APPROVED** [review]
:iapprove:
but some names are meh

**Comment by halotroop2288** [comment]
> :iapprove:
> but some names are meh

What? What names? These are intermediaries. 🤨

**Review by DeadlyMC — APPROVED** [review]

**Comment by hYdos** [comment]
no. the policy for intermediaries is that we dont take 3rd party pr's

**Comment by BluCobalt** [comment]
Either way, we still need intermediaries for 1.12.1.

**Comment by halotroop2288** [comment]
> Either way, we still need intermediaries for 1.12.1.

If **someone** else generates the exact same matches and intermediaries just to spite me, I'm going to be pissed.

**Comment by hYdos** [comment]
> Either way, we still need intermediaries for 1.12.1.

we need an actual plan for that. i might make a channel for discussion of that

**Comment by BluCobalt** [comment]
> > Either way, we still need intermediaries for 1.12.1.
> 
> we need an actual plan for that. i might make a channel for discussion of that

#dev-intermediaries?

**Comment by halotroop2288** [comment]
> we need an actual plan for that. i might make a channel for discussion of that

Or you can just reverse 624829de since there was no reason to remove that anyway.

**Pull request closed without merging**
